Create a 1-D array containing 10 values all zeros

In [4]:
import numpy as np
zeros = np.zeros((10,),dtype=int)
print(zeros)

[0 0 0 0 0 0 0 0 0 0]


A 2-D array called myarray2 using arange()
having 3 rows and 5 columns with start value = 4,
step size 4 and dtype as float.

In [3]:
## Type the code here
myarray2 = np.arange(4, 4 * 15 + 1, 4, dtype=float).reshape(3, 5)
print(myarray2)

[[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


A 2-D array called ones having 2 rows and 5
columns and all the elements are set to 1 and
dtype as int.

In [4]:
## Type the code here
ones = np.ones((10,), dtype=int).reshape(2, 5)
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]]


A 1-D array called vowels having the elements ‘a’,
‘e’, ‘i’, ‘o’ and ‘u’.

In [14]:
## Type the code here
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
print(vowels)

['a' 'e' 'i' 'o' 'u']


Use nested Python lists to create a 2-D array called
myarray1 having 3 rows and 3 columns and store
the following data:
2.7, -2, -19
0, 3.4, 99.9
10.6, 0, 13

In [6]:
## Type the code here
myarray1 = np.array([[2.7, -2, -19], [0, 3.4, 99.9], [10.6, 0, 13]])
print(myarray1)

[[  2.7  -2.  -19. ]
 [  0.    3.4  99.9]
 [ 10.6   0.   13. ]]


Using the arrays created in Question 4 above, write
NumPy commands for the following :
(a) Find the dimensions, shape, size, data type of the
items and itemsize of arrays zeros, vowels,
ones, myarray1 and myarray2.

In [13]:
## Type the code here

# Arrays (from previous questions)
zeros = np.zeros((10,), dtype=int)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
ones = np.ones((10,), dtype=int).reshape(2, 5)
myarray1 = np.array([[2.7, -2, -19], [0, 3.4, 99.9], [10.6, 0, 13]])
myarray2 = np.arange(4, 4 * 15 + 1, 4, dtype=float).reshape(3, 5)

# Function to display the required properties
def display_properties(array, name):
    print(f"Properties of {name}:")
    print(f"  Dimensions: {array.ndim}")
    print(f"  Shape: {array.shape}")
    print(f"  Size: {array.size}")
    print(f"  Data Type: {array.dtype}")
    print(f"  Item Size: {array.itemsize} bytes")
    print()

# Display properties for each array
display_properties(zeros, "zeros")
display_properties(vowels, "vowels")
display_properties(ones, "ones")
display_properties(myarray1, "myarray1")
display_properties(myarray2, "myarray2")

Properties of zeros:
  Dimensions: 1
  Shape: (10,)
  Size: 10
  Data Type: int64
  Item Size: 8 bytes

Properties of vowels:
  Dimensions: 1
  Shape: (5,)
  Size: 5
  Data Type: <U1
  Item Size: 4 bytes

Properties of ones:
  Dimensions: 2
  Shape: (2, 5)
  Size: 10
  Data Type: int64
  Item Size: 8 bytes

Properties of myarray1:
  Dimensions: 2
  Shape: (3, 3)
  Size: 9
  Data Type: float64
  Item Size: 8 bytes

Properties of myarray2:
  Dimensions: 2
  Shape: (3, 5)
  Size: 15
  Data Type: float64
  Item Size: 8 bytes



(b) Reshape the array ones to have all the 10 elements
in a single row.

In [15]:
## Type the code here
to_reshape_array = ones.reshape(1, 10)
print("Reshaped array ones into { single row }:")
print(to_reshape_array)

Reshaped array ones into { single row }:
[[1 1 1 1 1 1 1 1 1 1]]


(c) Display the 2nd and 3rd element of the array vowels.

In [18]:
## Type the code here
array_vowels = vowels[1:3]
print(array_vowels)

['e' 'i']


(d) Display all elements in the 2nd and 3rd row of the
array myarray1

In [26]:
## Type the code here
all_elements = myarray1[1:3, :]
print(all_elements)

[[ 0.   3.4 99.9]
 [10.6  0.  13. ]]


(e) Display the elements in the 1st and 2nd column of
the array myarray1.

In [31]:
## Type the code here
elements = myarray1[:, 0:2]
print(elements)

[[ 2.7 -2. ]
 [ 0.   3.4]
 [10.6  0. ]]


(f) Display the elements in the 1st column of the 2nd
and 3rd row of the array myarray1.

In [32]:
## Type the code here
elements_array = myarray1[1:3, 0]
print(elements_array)

[ 0.  10.6]


(g) Reverse the array of vowels.

In [34]:
## Type the code here
reverse_vowels = vowels[::-1]
print(reverse_vowels)

['u' 'o' 'i' 'e' 'a']


The file Marks.csv contains the marks of students in 4 subjects English,Physics,Math and Chemistry
(1) Load the marks into a 2-D array names Results

In [9]:
## Type the code here

results = np.loadtxt("Marks.csv", delimiter=",", skiprows=1)
print(results)

[[60. 70. 80. 90.]
 [75. 78. 92. 35.]
 [62. 79. 62. 57.]
 [69. 90. 74. 62.]]


(2)Find the highest mark in every subject

In [10]:
## Type the code here
highest = np.max(results, axis=0)
print(highest)

[75. 90. 92. 90.]


(3)Find the average mark of every student

In [ ]:
## Type the code here
average_marks = np.mean(results, axis=1)
print(average_marks)

[75.   70.   65.   73.75]
